version: '3.4'

services:
  bumaapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
    ports:
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bumaaudittrailservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ConnectionStrings__ConnectionString=XpoProvider=Postgres;Data Source=localhost:5432;Initial Catalog=postgres;User Id=postgres;Password=A46E7Cbuma2021!; 
    ports:
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bumaadministrationsservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ConnectionStrings__ConnectionString=XpoProvider=Postgres;Data Source=localhost:5432;Initial Catalog=postgres;User Id=postgres;Password=A46E7Cbuma2021!;
    ports:
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

      

